
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-32400}:32400"
    environment:
      - API_KEY=${API_KEY}
    volumes:
      - ${DB_BASE_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:32400/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s